# Generated by Django 2.2.12 on 2020-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='R123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='R456',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwdwedw', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RFFFFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rffff', models.BigIntegerField()),
            ],
        ),
    ]
